# SUYASH PRATAP SINGH

# About Notebook: This notebook covers some machine learning data structures like vectors, matrices and arrays and perform various operations on each of these data structures.



About Numpy Library:
It is foundation of python programming for machine learning.
Allows many efficient operations on data structures used in machine learning.
Data strutures used in machine learning are like vectors, matrices & Arrays

List of operations to perfom
Creating a vector (row vector & column vector)
Creating a Matrix
Creating a Sparse Matrix
Selecting Elements
Describing A Matrix
Applying Operations to Elements
Finding the Maximum & Minimum values
Calculating the avarage, variance and standard deviation
Reshaping Arrays
Transposing a vector or matrix
Flattening a Matrix
Finding the Rank of a Matrix
Calcutlating the Determinant
Getting the Diagonal of a Matrix
Calculating the Trace of a Matrix
Finding Eignevalues and Eigenvectors
Calculating Dot Products of Two Matrices
Adding and Subtracting Matrices
Multiplying Matrices
Invetting a Matrix
Generating Random values

# 1. Creating a vector

In [2]:
# load libray
import numpy as np

# create a vector as a row
vector_row = np.array([1,2,3])

# create a vector as a column
vector_column = np.array([[1],
                         [2],
                         [3]])

# view row vector
print(vector_row)
# view column vector
print(vector_column)

[1 2 3]
[[1]
 [2]
 [3]]


# 2. Creating a Matrix

In [3]:
# load library
import numpy as np

# create a matrix
matrix = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])

# view matrix
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
# Alternative way to create a matrix
matrix_object = np.mat([[1,2],
                       [3,4],
                       [5,6]])

matrix_object

matrix([[1, 2],
        [3, 4],
        [5, 6]])

# 3. Creating a Sparse Matrix

In [5]:
# load library
import numpy as np
from scipy import sparse

# create a matrix
matrix = np.array([[0,2,0],
                  [4,5,0],
                  [7,0,0]])

# create compressed sparse row(CSR) matrix
matrix_sparse = sparse.csr_matrix(matrix)

print(matrix)

[[0 2 0]
 [4 5 0]
 [7 0 0]]


In [6]:
print(matrix_sparse)

  (0, 1)	2
  (1, 0)	4
  (1, 1)	5
  (2, 0)	7


# 4. Selecting Elemeents

In [1]:
# load library
import numpy as np

# create matrix
matrix = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])

print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [2]:
# create row vector
vector = np.array([1,2,3,4,5,6])
print(vector)

[1 2 3 4 5 6]


In [3]:
# select element of the second row and third column of the matrix
matrix[1,2]

6

In [4]:
# select the 5th element of the vector
vector[4]

5

In [5]:
# select all the elements of vector
vector[:]

array([1, 2, 3, 4, 5, 6])

In [6]:
# select all the elements up to 4th element in vector
vector[:4]

array([1, 2, 3, 4])

In [7]:
# select all the elements after the first element in vector
vector[1:]

array([2, 3, 4, 5, 6])

In [8]:
# select last element of the vector
vector[-1]

6

In [9]:
# select the first two rows and all the columns of matrix
matrix[:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
# select all the rows and the second columns of matrix
matrix[:,1:2]

array([[2],
       [5],
       [8]])

# 5. Describing a Matrix

In [11]:
# creating a matrix
matrix = np.array([[10,11,12],
                  [13,14,15],
                  [16,17,18]])

In [12]:
# view the no. of rows and columns in matrix
matrix.shape

(3, 3)

In [13]:
# view the no. of dimensions of the matrix
matrix.ndim

2

# 6. Applying Operations on the elements

In [14]:
# create matrix
matrix = np.array([[1,2,3,4,5],
                 [6,7,8,9,10]])

In [15]:
# create a function that addes 100 to something
add_100 = lambda i:i+100

In [16]:
# create a vectorized fuction to add 100 to all the elements
vectorized_add_100=np.vectorize(add_100)

In [17]:
vectorized_add_100(matrix)

array([[101, 102, 103, 104, 105],
       [106, 107, 108, 109, 110]])

# 7. Finding the Maximum & Minimum values

In [18]:
# create a matrix
matrix = np.array([[11,12,13],
                  [14,15,16],
                  [17,18,19]])

In [19]:
# return the maximum element in the matrix
np.max(matrix)

19

In [20]:
# return the minimum element in the matrix
np.min(matrix)

11

# 8. Calculating the avarage, variance and standard deviation

In [21]:
# create a matrix
matrix = np.array([[12,13,15],
                  [13,54,65],
                  [11,4,5]])

In [22]:
# return average or meam of the matrix
np.mean(matrix)

21.333333333333332

In [23]:
# return the variance and standard deviation
np.std(matrix)

20.853989759489405

In [24]:
# return the variance of the matrix
np.var(matrix)

434.8888888888889

In [25]:
# find the min values in each column
np.mean(matrix, axis=0)

array([12.        , 23.66666667, 28.33333333])

In [26]:
# find the max values in each rows
np.mean(matrix, axis=1)

array([13.33333333, 44.        ,  6.66666667])

# 9.Reshaping Arrays 

In [27]:
# create a matix
# Create 4x3 matrix
matrix = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9],
                    [10, 11, 12]])

In [28]:
# reshape the matrix into 2x6 matix
matrix.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [29]:
# reshape the matix into 6x2
matrix.reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [30]:
# reshape the matrix into 12x1
matrix.reshape(12,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [31]:
# reshape the matrix into 1x12
matrix.reshape(1,12)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [32]:
# Alternative ways
matrix.size

12

In [33]:
matrix.reshape(1,-1) # for converting matrix into a row vector, here -1 represetns 'as many as needed'

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [34]:
matrix.reshape(matrix.size)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# 10. Transpose a vector or a matrix

In [35]:
# create a matrix
matrix = np.array([[1,3,4,5],
                  [3,54,6,7],
                  [23,56,7,8]])

In [36]:
# Transpose matrix
matrix.T

array([[ 1,  3, 23],
       [ 3, 54, 56],
       [ 4,  6,  7],
       [ 5,  7,  8]])

In [37]:
# create a vector
vector = np.array([1,4,1,4,6])

In [38]:
# transpose vector(it would be same as vector)
vector.T

array([1, 4, 1, 4, 6])

In [39]:
# create a row vector for converting its transpose into column vector (double[])
vector2 = np.array([[12,5,6,75,77]])

In [40]:
# transpose the row vector into column vector
vector2.T

array([[12],
       [ 5],
       [ 6],
       [75],
       [77]])

# 11. Flattening a Matrix

In [41]:
# create a matrix
matrix = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])

In [42]:
# flatten matrix
matrix.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
# alternative way to do it 
matrix.reshape(1,-1)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

# 12. Finding the Rank of a Matrix

In [44]:
# create matrix
matix = np.array([[1,1,1],
                 [1,1,10],
                 [1,1,15]])

In [45]:
# return rank of the matrix
np.linalg.matrix_rank(matrix)

2

# 13. Findign Determinant

In [46]:
# creating a matrix
matrix = np.array([[100,200,300],
                  [400,500,600],
                  [700,800,900]])

In [47]:
# return the diagonal of the matrix
matrix.diagonal()

array([100, 500, 900])

In [48]:
# return diagonal one above the main diagonal
matrix.diagonal(offset=1)

array([200, 600])

In [49]:
# return diagonal one below the main diagonal
matrix.diagonal(offset=-1)

array([400, 800])

# 15. Finding the trace of a matrix
Trace of a matrix means finding the sum of all the elements of a diagonal in a matrix

In [50]:
# create matrix
matrix = np.array([[11,12,13],
                  [13,14,15],
                  [16,17,18]])

In [51]:
# return the trace
matrix.trace()

43

In [52]:
# alternative way to do it
sum(matrix.diagonal())

43

# 16. Finding eigenvalues and eigenvectors
Formal definitoin of eigenvalues and eigenvectors

Av = λv

where, A is a square matrix λ is eigenvalues v is eigenvectors

In [53]:
# create matrix
m = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])

In [54]:
# finding eigenvalues and eigenvectors
e_values,e_vectors = np.linalg.eig(matix)

In [55]:
e_values

array([1.57972598e+01, 1.20274024e+00, 4.17207245e-17])

In [56]:
e_vectors

array([[ 9.35154454e-02,  9.54818342e-01,  7.07106781e-01],
       [ 5.61805577e-01,  2.83317939e-01, -7.07106781e-01],
       [ 8.21966761e-01, -8.97378394e-02, -4.99981379e-17]])

# 17. Finding dot product
we will find dot product of two vectors.

In [57]:
# create two vectors
v_a = np.array([1,2,4])
v_b = np.array([3,4,5])

In [58]:
# find dot product 
np.dot(v_a,v_b)

31

In [59]:
# alternative way to it (3.5+ version of python)
v_a@v_b

31

# 18. Adding and subtracting matrix

In [60]:
# create two matrices
m_a = np.array([[10,20,30],
               [40,50,60],
               [70,80,90]])
m_b = np.array([[90,80,70],
               [60,50,40],
               [30,20,10]])

In [61]:
# ADD
np.add(m_a, m_b)

array([[100, 100, 100],
       [100, 100, 100],
       [100, 100, 100]])

In [62]:
# subtract
np.subtract(m_a,m_b)

array([[-80, -60, -40],
       [-20,   0,  20],
       [ 40,  60,  80]])

In [63]:
# Alternative ways
m_a+m_b

array([[100, 100, 100],
       [100, 100, 100],
       [100, 100, 100]])

In [64]:
# Alternative ways
m_a-m_b

array([[-80, -60, -40],
       [-20,   0,  20],
       [ 40,  60,  80]])

# 19. Multiplication matices

In [65]:
# create matrix
m_a = np.array([[1,2],
               [2,1]])
m_b = np.array([[2,1],
               [1,2]])

In [66]:
# multiply
np.dot(m_a,m_b)

array([[4, 5],
       [5, 4]])

In [67]:
# alternative ways to do it
m_a @ m_b

array([[4, 5],
       [5, 4]])

In [68]:
# element wise multiplication
m_a * m_b

array([[2, 2],
       [2, 2]])

# 20. Invert Matrix
The inverse of a square matrix, A, is a second matrix A–1, such that: AA(power−1) = I where I is a Identity matrix.

In [69]:
# create a square matrix
m = np.array([[2,3],
              [2,4]])

In [70]:
# inverse matrix
np.linalg.inv(m)

array([[ 2. , -1.5],
       [-1. ,  1. ]])

In [71]:
# identity matrix
m @ np.linalg.inv(m)

array([[1., 0.],
       [0., 1.]])

# 21. Generate random values

In [72]:
# set seed
np.random.seed(0)

In [73]:
# generate 3 random numbers floats between 0.0 and 1.0
np.random.random(3)

array([0.5488135 , 0.71518937, 0.60276338])

In [74]:
# generate 20 random numbers floats between 0.0 and 1.0
np. random.random(20)

array([0.54488318, 0.4236548 , 0.64589411, 0.43758721, 0.891773  ,
       0.96366276, 0.38344152, 0.79172504, 0.52889492, 0.56804456,
       0.92559664, 0.07103606, 0.0871293 , 0.0202184 , 0.83261985,
       0.77815675, 0.87001215, 0.97861834, 0.79915856, 0.46147936])

In [75]:
# generate 5 random integers between 1 and 10
np.random.randint(0, 11, 5)

array([3, 3, 7, 0, 1])

In [76]:
# generate 5 random integers between 1 and 100
np.random.randint(0, 101, 5)

array([ 9, 57, 32, 31, 74])

# THANK YOU